[book]
authors = ["Opera_tive"]
language = "en"
multilingual = false
src = "src"
title = "Algorithm Book"

[output.html]
default-theme = "Coal"
git-repository-url = "https://github.com/Edgar907/algorithm-book"
mathjax-support = true
site-url = "/algorithm-book/"